- hosts: localhost
  connection: local
  gather_facts: no
  become_user: no
  roles:
    - git
    - xcode
    - dotfiles
    - homebrew_tap
    - homebrew_cask
    - homebrew
    - anyenv
    - atom

#    - jenv
