---
- name: git configuration author and email
  shell: git config --global user.name "{{ item.name }}" && git config --global user.email "{{ item.email }}"
  register: result
  with_items:
    - "{{ git_configuarion }}"
