---
homebrew_packages:
  - { name: ansible }
#  - { name: apache-spark }
  - { name: apachetop }
##  - { name: apple-gcc42 }
  - { name: autoconf }
  - { name: automake }
## - { name: avr-binutils }
  - { name: avrdude }
  - { name: bash }
##  - { name: class-dump }
  - { name: ctags }
  - { name: cmake }
  - { name: csshx }
  - { name: ems-flasher }
#  - { name: erlang }
  - { name: faac }
  - { name: ffmpeg } # brew install ffmpeg --with-vpx --with-vorbis --with-libvorbis --with-vpx --with-vorbis --with-theora --with-libogg --with-libvorbis --with-gpl --with-version3 --with-nonfree --with-postproc --with-libaacplus --with-libass --with-libcelt --with-libfaac --with-libfdk-aac --with-libfreetype --with-libmp3lame --with-libopencore-amrnb --with-libopencore-amrwb --with-libopenjpeg --with-openssl --with-libopus --with-libschroedinger --with-libspeex --with-libtheora --with-libvo-aacenc --with-libvorbis --with-libvpx --with-libx264 --with-libxvid
  - { name: flac }
##  - { name: fontconfig }
  - { name: gcc }
  - { name: gdb }
###  - { name: gdbm }
#  - { name: gettext }
  - { name: gibo }
  - { name: git }
  - { name: git-flow }
  - { name: glib }
#  - { name: global }
  - { name: gmp }
  - { name: gnutls }
  - { name: google-perftools }
  - { name: gperftools }
#  - { name: hadoop }
#  - { name: htop-osx }
  - { name: httpd }
  - { name: ifstat }
  - { name: imagemagick }
  - { name: jack }
  - { name: jadx }
####  - { name: jenv }
#  - { name: jenkins }
  - { name: jpeg }
  - { name: jq }
# - { name: kafka }
  - { name: kubectl }
  - { name: lame }
  - { name: mas }
#  - { name: maven }
  - { name: mcrypt }
  - { name: md5sha1sum }
  - { name: memcached }
  - { name: mysql }
####  - { name: ndenv }
####  - { name: node-build }
  - { name: nginx }
  - { name: openssl }
  - { name: pkg-config }
  - { name: postgresql }
####  - { name: pyenv }
  - { name: r }
##  - { name: rar }
####  - { name: rbenv }
  - { name: readline }
#  - { name: redis }
  - { name: rename }
####  - { name: ruby-build }
#  - { name: scalaenv }
  - { name: sqlite }
  - { name: tmux }
  - { name: unrar }
  - { name: vegeta }
  - { name: vim }
  - { name: wget }
  - { name: xhyve }
  - { name: xvid }
  - { name: youtube-dl }
  - { name: zlib }
# for phpenv
  - { name: freetype }
  - { name: gettext }
  - { name: icu4c }
  - { name: jpeg }
  - { name: libpng }
  - { name: libxml2 }
  - { name: unixodbc }
  - { name: readline }
  - { name: openssl }
  - { name: re2c }
  - { name: libmcrypt }
  - { name: autoconf }
  - { name: automake }

#  - { name: homebrew/apache/httpd22 }
#  - { name: caskroom/cask/rar }
#  - { name: caskroom/cask/jad }
